spring:
  application:
    name: 'user-service-api'
  data:
    mongodb:
      uri: 'mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${MONGO_DB}?retryWrites=true&w=majority&appName=cluster-help-desk'
      auto-index-creation: true
springdoc:
  openapi:
    title: 'User Service API'
    description: 'Componente responsável por gerenciar usuários do sistema.'
    version: '1.0.0'