spring:
  application:
    name: 'auth-service-api'
  data:
    mongodb:
      uri: 'mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${MONGO_DB}?retryWrites=true&w=majority&appName=cluster-help-desk'
jwt.secret: ${JWT_SECRET}
jwt.expiration: 120000
